[package]
name = "rwh"
categories = ["command-line-utilities"]

version.workspace = true
authors.workspace = true
description.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "rwh"
path = "src/main.rs"

[package.metadata.binstall]
pkg-url = "{repo}/releases/download/{version}/rwh.tgz"
pkg-fmt = "Tgz"
disabled-strategies = ["quick-install", "compile"]
target-family = "Linux"
target-arch = "X86_64"

[dependencies]
async-channel = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
serde_derive = { workspace = true }
url = { workspace = true, features = ["serde"] }
futures = { workspace = true }
rand = { workspace = true }
smol = { workspace = true }

# CLI specific dependencies
rwhlib = { path = "..", features = ["futures-rustls-native-certs"] }
clap = { workspace = true, features = ["cargo", "derive", "help", "env"] }
clap_complete = { workspace = true }
env_logger = { workspace = true }
console = { workspace = true }
indicatif = { workspace = true }
dialoguer = { workspace = true, features = ["completion"] }
color-eyre = { workspace = true }
unit-prefix = { workspace = true }
ctrlc = { workspace = true }
qr2term = { workspace = true }
arboard = { optional = true, workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
trycmd = { workspace = true }

[features]
clipboard = ["dep:arboard"]
# Enable experimental transfer-v2 support. The protocol is not yet finalized and is subject to change.
experimental-transfer-v2 = ["rwhlib/experimental-transfer-v2"]
experimental = ["experimental-transfer-v2"]

default = ["clipboard", "rwhlib/default", "rwhlib/forwarding"]
all = ["default"]
