[alias]
rel = "build --release"
inst = "install --path ."
clip = "clippy --release"
pub = "publish"
up = "update --verbose"

[build]
target = "x86_64-unknown-linux-musl"

[install]
target = "x86_64-unknown-linux-musl"

[publish]
target = "x86_64-unknown-linux-musl"

[clippy]
target = "x86_64-unknown-linux-musl"

[update]
target = "x86_64-unknown-linux-musl"

[target.'cfg(all())']
rustflags = [ "-Ctarget-feature=+crt-static", "-Ctarget-cpu=generic"]

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
