[alias]
rel = "build --release --target x86_64-unknown-linux-musl --bin rwh"
inst = "install --target x86_64-unknown-linux-musl --path ."
clip = "clippy --release --all-targets --features all"
pub = "publish"
up = "update --verbose"

[target.x86_64-unknown-linux-musl]
rustflags = [ "-Ctarget-feature=+crt-static", "-Ctarget-cpu=generic"]

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
